### ISSUE TITLE
Glob patterns not working for --spec parameter

### ISSUE THREAD

**Issue by Moke96** [currents-dev/cypress-currents-reporter#150]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-cloud/issues) and [discussions](https://github.com/currents-dev/cypress-cloud/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

n/a

### Describe the bug

**Cypress-Cloud:**
 `yarn cypress-cloud run --project ./cypress/cypress_e2e --browser chrome --spec "./cypress/cypress_e2e/cypress/e2e/Specs/!(test1.spec.ts|test2.spec.ts)"`

` WARNING  Found no spec files. Was looking for spec files that match both configSpecPattern and specPattern relative to projectRoot. Configuration: {
  projectRoot: 'myProjectPath\\frontend\\cypress\\cypress_e2e',
  specPattern: [
    './cypress/cypress_e2e/cypress/e2e/Specs/!(test1.spec.ts|test2.spec.ts)'
  ],
  configSpecPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
  excludeSpecPattern: [ '*.hot-update.js' ],
  testingType: 'e2e'
}`

**Plain Cypress:**
 `yarn cypress run --project ./cypress/cypress_e2e --browser chrome --spec "./cypress/cypress_e2e/cypress/e2e/Specs/!(test1.spec.ts|test2.spec.ts)"`

` (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.13.0                                                                        │
  │ Browser:        Chrome 114 (headless)                                                          │
  │ Node Version:   v16.15.0 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          17 found (test3.spec.ts,test4.spec.ts, ...)                                                    │
  │ Searched:       myProjectPath\frontend\cypress\cypress_e2e\cypress\e2e\Sp │
  │                 ecs\!(test1.spec.ts|test2.spec.ts)                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘`

Maybe related to https://github.com/currents-dev/cypress-cloud/issues/118

### Expected behavior

Glob patterns work with cypress cloud

### Command and Setup

 `yarn cypress-cloud run --project ./cypress/cypress_e2e --browser chrome --spec "./cypress/cypress_e2e/cypress/e2e/Specs/!(test1.spec.ts|test2.spec.ts)"`

### Full log and debug output

<details>

```
// Put your logs below this line


```

</details>

**Comment by agoldis** [comment]
@Moke96 you missed the full log and debug output
